[supervisord]
nodaemon=true
user=root

[program:asf]
command=/bin/sh -c 'rm -f /app/config/ASF.db && exec ArchiSteamFarm --no-restart'
directory=/app
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=10

[program:marketapp]
command=market-app --no-sandbox --headless --api-docs --api-host 0.0.0.0 --api-port 3000
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0